version: "3.5"

#  6100 - auth
#  6101 - db_auth
#  6200 - data
#  6201 - db_data  
services:

  auth:
    build: ./auth
    container_name: auth
    ports:
      - 6160:6100
    environment:
      - SERCRET_KEY=SERCRET_KEY
      - PORT=6100
      - DB_USERNAME=admin
      - DB_PASSWORD=root
      - DB_HOST=db_auth
      - DB_PORT=6101
      - DB_NAME=postgres
    depends_on:
      - db_auth
    networks:
      - internal_net

  db_auth:
    container_name: db_auth
    ports:
      - "6101:6101"
    environment:
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_USER=admin"
    image: postgres:14.5-alpine3.16
    command:
      - "postgres"
      - "-c"
      - "port=6101"
    volumes:
      - db_auth_vol:/var/lib/postgresql/data/
    networks:
      - internal_net

  db_data:
    container_name: db_data
    ports:
      - "6201:6201"
    environment:
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_USER=admin"
    image: postgres:14.5-alpine3.16
    command:
      - "postgres"
      - "-c"
      - "port=6201"
    volumes:
      - db_data_vol:/var/lib/postgresql/data/
    networks:
      - internal_net
    # image: postgres:15.1-alpine

volumes:
  db_auth_vol: {}
  db_data_vol: {}

networks:
  internal_net:
    driver: bridge
